In [1]:
#Dependencies
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
from sqlalchemy import Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
import csv

In [15]:
file_RE = "Resources/generation_annual_RE.csv"

In [16]:
renewable_df = pd.read_csv(file_RE)

In [18]:
renewable_df[]

,YEAR,STATE_CODE,SECTOR_NAME,ENERGY_SOURCE,GENERATION \n (Megawatthours)
0,1990,AK,Total Electric Power Industry,Coal,"510,573"
1,1990,AK,Total Electric Power Industry,Petroleum,"497,116"
2,1990,AK,Total Electric Power Industry,Natural Gas,"3,466,261"
3,1990,AK,Total Electric Power Industry,Hydroelectric Conventional,"974,521"
4,1990,AK,Total Electric Power Industry,Wind,0
5,1990,AK,Total Electric Power Industry,Wood and Wood Derived Fuels,"151,035"
6,1990,AK,Total Electric Power Industry,Total,"5,599,506"
7,1990,AK,"Electric Generators, Electric Utilities",Coal,"311,960"
8,1990,AK,"Electric Generators, Electric Utilities",Petroleum,"336,905"
9,1990,AK,"Electric Generators, Electric Utilities",Natural Gas,"2,869,638"
10,1990,AK,"Electric Generators, Electric Utilities",Hydroelectric Conventional,"974,521"
11,1990,AK,"Electric Generators, Electric Utilities",Wind,0
12,1990,AK,"Electric Generators, Electric Utilities",Total,"4,493,024"
13,1990,AK,"Combined Heat and Power, Commercial Power",Coal,"198,613"
14,1990,AK,"Combined Heat and Power, Commercial Power",Petroleum,"66,920"
15,1990,AK,"Combined Heat and Power, Commercial Power",Total,"265,533"
16,1990,AK,"Combined Heat and Power, Industrial Power",Petroleum,"93,291"
17,1990,AK,"Combined Heat and Power, Industrial Power",Natural Gas,"596,623"
18,1990,AK,"Combined Heat and Power, Industrial Power",Wood and Wood Derived Fuels,"151,035"
19,1990,AK,"Combined Heat and Power, Industrial Power",Total,"840,949"
20,1990,AL,Total Electric Power Industry,Coal,"53,658,115"
21,1990,AL,Total Electric Power Industry,Petroleum,"138,089"
22,1990,AL,Total Electric Power Industry,Natural Gas,"1,020,714"
23,1990,AL,Total Electric Power Industry,Other Gases,"269,476"
24,1990,AL,Total Electric Power Industry,Nuclear,"12,051,882"
25,1990,AL,Total Electric Power Industry,Hydroelectric Conventional,"10,366,507"
26,1990,AL,Total Electric Power Industry,Wood and Wood Derived Fuels,"2,099,847"
27,1990,AL,Total Electric Power Industry,Other Biomass,"47,503"
28,1990,AL,Total Electric Power Industry,Total,"79,652,133"
29,1990,AL,"Electric Generators, Electric Utilities",Coal,"53,301,276"
30,1990,AL,"Electric Generators, Electric Utilities",Petroleum,"91,916"
31,1990,AL,"Electric Generators, Electric Utilities",Natural Gas,"420,115"
32,1990,AL,"Electric Generators, Electric Utilities",Nuclear,"12,051,882"
33,1990,AL,"Electric Generators, Electric Utilities",Hydroelectric Conventional,"10,366,507"
34,1990,AL,"Electric Generators, Electric Utilities",Total,"76,231,696"
35,1990,AL,"Electric Generators, Independent Power Producers",Wood and Wood Derived Fuels,"2,626"
36,1990,AL,"Electric Generators, Independent Power Producers",Other Biomass,"25,310"
37,1990,AL,"Electric Generators, Independent Power Producers",Total,"27,936"
38,1990,AL,"Combined Heat and Power, Electric Power",Coal,"42,598"
39,1990,AL,"Combined Heat and Power, Electric Power",Natural Gas,"33,538"
40,1990,AL,"Combined Heat and Power, Electric Power",Wood and Wood Derived Fuels,"589,677"
41,1990,AL,"Combined Heat and Power, Electric Power",Total,"665,813"
42,1990,AL,"Combined Heat and Power, Industrial Power",Coal,"314,241"
43,1990,AL,"Combined Heat and Power, Industrial Power",Petroleum,"46,173"
44,1990,AL,"Combined Heat and Power, Industrial Power",Natural Gas,"567,061"
45,1990,AL,"Combined Heat and Power, Industrial Power",Other Gases,"269,476"
46,1990,AL,"Combined Heat and Power, Industrial Power",Wood and Wood Derived Fuels,"1,507,544"
47,1990,AL,"Combined Heat and Power, Industrial Power",Other Biomass,"22,193"
48,1990,AL,"Combined Heat and Power, Industrial Power",Total,"2,726,688"
49,1990,AR,Total Electric Power Industry,Coal,"19,207,935"
50,1990,AR,Total Electric Power Industry,Petroleum,"79,979"
51,1990,AR,Total Electric Power Industry,Natural Gas,"3,578,573"
52,1990,AR,Total Electric Power Industry,Nuclear,"11,282,053"
53,1990,AR,Total Electric Power Industry,Hydroelectric Conventional,"3,654,653"
54,1990,AR,Total Electric Power Industry,Wood and Wood Derived Fuels,"1,238,044"
55,1990,AR,Total Electric Power Industry,Other Biomass,"15,389"
56,1990,AR,Total Electric Power Industry,Pumped Storage,"42,972"
57,1990,AR,Total Electric Power Industry,Total,"39,099,598"
58,1990,AR,"Electric Generators, Electric Utilities",Coal,"19,160,989"
59,1990,AR,"Electric Generators, Electric Utilities",Petroleum,"73,856"

In [19]:
indexNames = renewable_df[ (renewable_df['ENERGY_SOURCE'] != "Hydroelectric Conventional") & (renewable_df['ENERGY_SOURCE'] != "Wind") ].index
renewable_df.drop(indexNames , inplace=True)

In [3]:
RE_prod_df = pd.read_csv(file_one)

In [4]:
RE_prod_df

,Year,State Code,Producer Type,Fuel Source,Generators,Facilities,Nameplate Capacity (Megawatts),Summer Capacity (Megawatts)
0,1990,AK,"Combined Heat and Power, Commercial Power",All Sources,NaN,4,85.9,80.1
1,1990,AK,"Combined Heat and Power, Commercial Power",Coal,NaN,3,65.5,61.1
2,1990,AK,"Combined Heat and Power, Commercial Power",Petroleum,NaN,1,20.4,19.0
3,1990,AK,"Combined Heat and Power, Industrial Power",All Sources,NaN,23,229.4,204.2
4,1990,AK,"Combined Heat and Power, Industrial Power",Natural Gas,NaN,28,159.3,136.7
...,...,...,...,...,...,...,...,...
40894,2016,WY,Total Electric Power Industry,Natural Gas,26,10,306.4,260.5
40895,2016,WY,Total Electric Power Industry,Other,1,1,11.5,11.5
40896,2016,WY,Total Electric Power Industry,Other Gases,7,3,111.7,110.1
40897,2016,WY,Total Electric Power Industry,Petroleum,4,3,5.8,5.8
40898,2016,WY,Total Electric Power Industry,Wind,31,21,"1,487.3","1,487.3"

In [5]:
RE_prod_df[RE_prod_df["Year"]> 2000]

,Year,State Code,Producer Type,Fuel Source,Generators,Facilities,Nameplate Capacity (Megawatts),Summer Capacity (Megawatts)
15039,2001,AK,"Combined Heat and Power, Commercial Power",All Sources,NaN,6,53.0,34.0
15040,2001,AK,"Combined Heat and Power, Commercial Power",Coal,NaN,2,36.0,17.0
15041,2001,AK,"Combined Heat and Power, Commercial Power",Petroleum,NaN,4,18.0,17.0
15042,2001,AK,"Combined Heat and Power, Electric Power",All Sources,NaN,3,63.0,50.0
15043,2001,AK,"Combined Heat and Power, Electric Power",Coal,NaN,2,54.0,44.0
...,...,...,...,...,...,...,...,...
40894,2016,WY,Total Electric Power Industry,Natural Gas,26,10,306.4,260.5
40895,2016,WY,Total Electric Power Industry,Other,1,1,11.5,11.5
40896,2016,WY,Total Electric Power Industry,Other Gases,7,3,111.7,110.1
40897,2016,WY,Total Electric Power Industry,Petroleum,4,3,5.8,5.8
40898,2016,WY,Total Electric Power Industry,Wind,31,21,"1,487.3","1,487.3"

In [6]:
RE_prod_df.tail(30)

,Year,State Code,Producer Type,Fuel Source,Generators,Facilities,Nameplate Capacity (Megawatts),Summer Capacity (Megawatts)
40869,2016,WV,Total Electric Power Industry,Coal,21,11,"13,510.9","12,958.0"
40870,2016,WV,Total Electric Power Industry,Hydroelectric,37,12,370.6,349.5
40871,2016,WV,Total Electric Power Industry,Natural Gas,18,4,"1,339.4","1,194.3"
40872,2016,WV,Total Electric Power Industry,Other,3,3,65.5,65.5
40873,2016,WV,Total Electric Power Industry,Petroleum,1,1,18.5,11.0
40874,2016,WV,Total Electric Power Industry,Wind,7,6,686.3,686.3
40875,2016,WY,"Electric Generators, Electric Utilities",All Sources,86,39,"8,327.3","7,444.7"
40876,2016,WY,"Electric Generators, Electric Utilities",Coal,19,9,"7,093.1","6,250.0"
40877,2016,WY,"Electric Generators, Electric Utilities",Hydroelectric,31,15,300.5,304.5
40878,2016,WY,"Electric Generators, Electric Utilities",Natural Gas,15,6,287.5,244.0
40879,2016,WY,"Electric Generators, Electric Utilities",Petroleum,3,2,4.7,4.7
40880,2016,WY,"Electric Generators, Electric Utilities",Wind,18,8,641.5,641.5
40881,2016,WY,"Electric Generators, Independent Power Producers",All Sources,15,15,938.7,933.4
40882,2016,WY,"Electric Generators, Independent Power Producers",Coal,1,1,90.0,85.0
40883,2016,WY,"Electric Generators, Independent Power Producers",Hydroelectric,1,1,2.9,2.6
40884,2016,WY,"Electric Generators, Independent Power Producers",Wind,13,13,845.8,845.8
40885,2016,WY,Industrial Power,All Sources,28,9,214.2,215.8
40886,2016,WY,Industrial Power,Coal,8,2,71.0,76.6
40887,2016,WY,Industrial Power,Natural Gas,11,4,18.9,16.5
40888,2016,WY,Industrial Power,Other,1,1,11.5,11.5
40889,2016,WY,Industrial Power,Other Gases,7,3,111.7,110.1
40890,2016,WY,Industrial Power,Petroleum,1,1,1.1,1.1
40891,2016,WY,Total Electric Power Industry,All Sources,129,63,"9,480.2","8,593.9"
40892,2016,WY,Total Electric Power Industry,Coal,28,12,"7,254.1","6,411.6"
40893,2016,WY,Total Electric Power Industry,Hydroelectric,32,16,303.4,307.1
40894,2016,WY,Total Electric Power Industry,Natural Gas,26,10,306.4,260.5
40895,2016,WY,Total Electric Power Industry,Other,1,1,11.5,11.5
40896,2016,WY,Total Electric Power Industry,Other Gases,7,3,111.7,110.1
40897,2016,WY,Total Electric Power Industry,Petroleum,4,3,5.8,5.8
40898,2016,WY,Total Electric Power Industry,Wind,31,21,"1,487.3","1,487.3"

In [7]:
print(RE_prod_df.loc[RE_prod_df['Fuel Source'].isin(['Wind','Hydroelectric', 'All Sources'])])

       Year State Code                                     Producer Type  \
0      1990         AK         Combined Heat and Power, Commercial Power
3      1990         AK         Combined Heat and Power, Industrial Power
7      1990         AK           Electric Generators, Electric Utilities
9      1990         AK           Electric Generators, Electric Utilities
12     1990         AK           Electric Generators, Electric Utilities
...     ...        ...                                               ...
40884  2016         WY  Electric Generators, Independent Power Producers
40885  2016         WY                                  Industrial Power
40891  2016         WY                     Total Electric Power Industry
40893  2016         WY                     Total Electric Power Industry
40898  2016         WY                     Total Electric Power Industry

         Fuel Source Generators Facilities Nameplate Capacity (Megawatts)  \
0        All Sources        NaN          4                           85.9
3        All Sources        NaN         23                          229.4
7        All Sources        NaN        125                        1,754.7
9      Hydroelectric        NaN         20                          240.7
12              Wind        NaN          1                             .0
...              ...        ...        ...                            ...
40884           Wind         13         13                          845.8
40885    All Sources         28          9                          214.2
40891    All Sources        129         63                        9,480.2
40893  Hydroelectric         32         16                          303.4
40898           Wind         31         21                        1,487.3

      Summer Capacity (Megawatts)
0                            80.1
3                           204.2
7                         1,541.8
9                           235.7
12                             .0
...                           ...
40884                       845.8
40885                       215.8
40891                     8,593.9
40893                       307.1
40898                     1,487.3

[13310 rows x 8 columns]

In [8]:
RE_prod_df.drop(['Producer Type'], axis=1)

,Year,State Code,Fuel Source,Generators,Facilities,Nameplate Capacity (Megawatts),Summer Capacity (Megawatts)
0,1990,AK,All Sources,NaN,4,85.9,80.1
1,1990,AK,Coal,NaN,3,65.5,61.1
2,1990,AK,Petroleum,NaN,1,20.4,19.0
3,1990,AK,All Sources,NaN,23,229.4,204.2
4,1990,AK,Natural Gas,NaN,28,159.3,136.7
...,...,...,...,...,...,...,...
40894,2016,WY,Natural Gas,26,10,306.4,260.5
40895,2016,WY,Other,1,1,11.5,11.5
40896,2016,WY,Other Gases,7,3,111.7,110.1
40897,2016,WY,Petroleum,4,3,5.8,5.8
40898,2016,WY,Wind,31,21,"1,487.3","1,487.3"

In [9]:
RE_prod_df.head(100)

,Year,State Code,Producer Type,Fuel Source,Generators,Facilities,Nameplate Capacity (Megawatts),Summer Capacity (Megawatts)
0,1990,AK,"Combined Heat and Power, Commercial Power",All Sources,NaN,4,85.9,80.1
1,1990,AK,"Combined Heat and Power, Commercial Power",Coal,NaN,3,65.5,61.1
2,1990,AK,"Combined Heat and Power, Commercial Power",Petroleum,NaN,1,20.4,19.0
3,1990,AK,"Combined Heat and Power, Industrial Power",All Sources,NaN,23,229.4,204.2
4,1990,AK,"Combined Heat and Power, Industrial Power",Natural Gas,NaN,28,159.3,136.7
...,...,...,...,...,...,...,...,...
95,1990,CA,"Combined Heat and Power, Electric Power",Coal,NaN,5,289.7,271.4
96,1990,CA,"Combined Heat and Power, Electric Power",Natural Gas,NaN,49,"2,661.4","2,280.9"
97,1990,CA,"Combined Heat and Power, Electric Power",Other Biomass,NaN,NaN,14.4,13.4
98,1990,CA,"Combined Heat and Power, Electric Power",Wood and Wood Derived Fuels,NaN,2,24.0,22.5
99,1990,CA,"Combined Heat and Power, Industrial Power",All Sources,NaN,102,"2,567.2","2,251.9"

In [10]:
RE_prod_df.tail(77
               )

,Year,State Code,Producer Type,Fuel Source,Generators,Facilities,Nameplate Capacity (Megawatts),Summer Capacity (Megawatts)
40822,2016,WI,"Electric Generators, Electric Utilities",Wood and Wood Derived Fuels,7,4,181.9,143.0
40823,2016,WI,"Electric Generators, Independent Power Producers",All Sources,100,29,"2,168.2","1,973.1"
40824,2016,WI,"Electric Generators, Independent Power Producers",Hydroelectric,26,8,19.8,19.6
40825,2016,WI,"Electric Generators, Independent Power Producers",Natural Gas,3,1,561.0,471.0
40826,2016,WI,"Electric Generators, Independent Power Producers",Nuclear,2,1,"1,286.0","1,192.6"
...,...,...,...,...,...,...,...,...
40894,2016,WY,Total Electric Power Industry,Natural Gas,26,10,306.4,260.5
40895,2016,WY,Total Electric Power Industry,Other,1,1,11.5,11.5
40896,2016,WY,Total Electric Power Industry,Other Gases,7,3,111.7,110.1
40897,2016,WY,Total Electric Power Industry,Petroleum,4,3,5.8,5.8
40898,2016,WY,Total Electric Power Industry,Wind,31,21,"1,487.3","1,487.3"

In [11]:
indexNames = RE_prod_df[ (RE_prod_df['Fuel Source'] == Petroleum) & (RE_prod_df['Fuel Source'] == Other Gases) & (RE_prod_df['Fuel Source'] == Other) & (RE_prod_df['Fuel Source'] == Natural Gas) & (RE_prod_df['Fuel Source'] == Coal)
& (RE_prod_df['Fuel Source'] == Wood and Wood Derived Fuels) & (RE_prod_df['Fuel Source'] == Other Biomass) & (RE_prod_df['Fuel Source'] == Nuclear)].index
    
RE_prod_df.drop(indexNames , inplace=True)

SyntaxError: invalid syntax (<ipython-input-11-4977e2cefac7>, line 1)